### ISSUE TITLE
Ardupilot Compass ID for Dual Here3

### ISSUE THREAD

**Issue by bobbywatts** [wattsinnovations/PRISM-releases#1]
Woohoo! Figured out the CompassID stuff. We will program each of the HERE3 compasses before installing. Once programmed, I managed to get two orange cubes with 4 Here3's (2 for each machine) to register correctly. 

I would say that we should hard code these into the Ardupilot FW, but I do believe down the road we will offer the HerePro GNSS modules. So--- I'm thinking we should just make a Compass menu where you choose which compasses we have. Then it will automatically assign these values. Or for now - we could hard code it. Thoughts?

Here are the parameters for dual Here3's on CAN:

COMPASS_DEV_ID | 590114
COMPASS_DEV_ID2 | 97539
COMPASS_DEV_ID3 | 97283
COMPASS_PRIO1_ID | 97539
COMPASS_PRIO2_ID | 97283
COMPASS_PRIO3_ID | 590114

**Comment by dakejahl** [comment]
this is wrong repo lol
